defaults:
  - hydra/sweeper/sampler: NSGAIISampler
  - override hydra/sweeper: OptunaPruningSweeper
  - _self_

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: [minimize, minimize]
    study_name: multi-objective
    storage: null
    n_trials: 20
    n_jobs: 1
    params:
      x: range(0, 5, step=0.5)
      y: range(0, 3, step=0.5)

x: 1
y: 1
