defaults:
  - hydra/sweeper/sampler: TPESampler
  - override hydra/sweeper: OptunaPruningSweeper
  - _self_

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: custom-search-space
    storage: null
    n_trials: 10
    n_jobs: 1

    params:
      x: tag("1", interval(-5, 5))
      y: tag(0:3, 1:4, interval(-5, 5))
    # `custom_search_space` should either refer to a single
    # implementation of the class `CustomSearchSpace` or
    # to a list of these.
    custom_search_space:
      _target_: objective.MyCustomSearchSpace

x: 1
y: 1
z: 100
max_z_difference_from_x: 0.5
