defaults:
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: custom-search-space
    storage: null
    n_trials: 10
    n_jobs: 1

    params:
      +x: tag(0:1, 1:2, interval(-5, 5))
      +y: tag(0:3, 1:4, interval(-5, 5))
    # `custom_search_space` should be a dotpath pointing to a
    # callable that provides search-space configuration logic:
    custom_search_space: objective.configure

max_z_difference_from_x: 0.5
